### ISSUE TITLE
重定向解析成Url出错，比如重定向为/，这时走setUrl函数时，无法解析。

### ISSUE THREAD

**Issue by HeKunTong** [easy-swoole/http-client#16]
Fatal error: Uncaught TypeError: Argument 1 passed to EasySwoole\Spl\SplBean::__construct() must be of the type array or null, boolean given, called in /root/develop/test/vendor/easyswoole/http-client/src/HttpClient.php on line 129 and defined in /root/develop/test/vendor/easyswoole/spl/src/SplBean.php:26
Stack trace:
#0 /root/develop/test/vendor/easyswoole/http-client/src/HttpClient.php(129): EasySwoole\Spl\SplBean->__construct(false)
#1 /root/develop/test/vendor/easyswoole/http-client/src/HttpClient.php(531): EasySwoole\HttpClient\HttpClient->setUrl('/')
#2 /root/develop/test/vendor/easyswoole/http-client/src/HttpClient.php(548): EasySwoole\HttpClient\HttpClient->rawRequest('GET')
#3 /root/develop/test/test.php(14): EasySwoole\HttpClient\HttpClient->get()

**Comment by HeKunTong** [comment]
// 处理重定向
        if (($client->statusCode == 301 || $client->statusCode == 302) && (($this->followLocation > 0) && ($this->redirected < $this->followLocation))) {
            $this->redirected++;
            $location = $client->headers['location'];
            $info = parse_url($location);
            // scheme 为空 没有域名
            if (empty($info['scheme']) && empty($info['host'])) {
                $this->url->setPath($location);
                $this->parserUrlInfo();
            } else {
                // 去除//开头的跳转域名
                $location = ltrim($location,'//');
                $this->setUrl($location);
                $this->httpClient = null;
            }
            return $this->rawRequest($httpMethod, $rawData, $contentType);
        }else{
            $this->redirected = 0;
        }
